version: "3.7"

services:
  container-ci:
    image: jnijhof/container-ci:0.0.1
    ports:
      - 9292:9292
    depends_on:
      - redis
    deploy:
      mode: replicated
      replicas: 1
      restart_policy:
        condition: on-failure
      placement:
        constraints:
          - node.role == worker
      resources:
        limits:
          memory: 512M
        reservations:
          memory: 512M

  container-ci-worker:
    image: jnijhof/container-ci:0.0.1
    environment:
      - QUEUE=*
    entrypoint: ['bundle', 'exec', 'rake', 'resque:work']
    depends_on:
      - redis
    deploy:
      mode: replicated
      replicas: 1
      restart_policy:
        condition: on-failure
      placement:
        constraints:
          - node.role == worker
      resources:
        limits:
          memory: 512M
        reservations:
          memory: 512M
    volumes:
      - type: bind
        source: /var/run/docker.sock
        target: /var/run/docker.sock

  redis:
    image: redis:alpine
    deploy:
      mode: replicated
      replicas: 1
      restart_policy:
        condition: on-failure
      placement:
        constraints:
          - node.role == worker
      resources:
        limits:
          memory: 512M
        reservations:
          memory: 512M
